# Midterm Manure Q1 Benchmark

Local VS Code notebook for evaluating ChatbotLP on Midterm Problem 1, Question 1: Manure Management.

In [1]:
from pathlib import Path
import sys

REPO_ROOT = Path.cwd().resolve()
while REPO_ROOT != REPO_ROOT.parent and not (REPO_ROOT / "src").exists():
    REPO_ROOT = REPO_ROOT.parent

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

REPO_ROOT

PosixPath('/Users/mgomezochoa/Documents/ChatbotLP')

In [2]:
import os
os.environ["GEMINI_API_KEY"] = ""
os.environ["LLM_PROVIDER"] = "gemini"
os.environ["GEMINI_MODEL"] = "gemini-3-flash-preview"

In [3]:
import json
import pandas as pd
from IPython.display import Markdown, display

from src.midterm_benchmark import (
    MidtermBenchmarkConfig,
    load_benchmark_files,
    run_midterm_manure_q1_benchmark,
    write_midterm_outputs,
)

## Problem Statement And Reference Solution

In [4]:
files = load_benchmark_files()
reference = files["reference_solution"]

display(Markdown(files["problem_statement"]))

reference_summary = pd.DataFrame([
    {"metric": "objective_value", "value": reference["objective_value"]},
    {"metric": "demand_revenue", "value": reference["demand_revenue"]},
    {"metric": "transport_cost", "value": reference["transport_cost"]},
    {"metric": "supply_cost", "value": reference["supply_cost"]},
])
display(reference_summary)
display(reference)

# Problem 1, Question 1: Manure Management

A dairy farm in Eau Claire produces 1000 tons of waste manure and wants to get
rid of it. The farmer is willing to give the manure away for free.

A corn farmer in Menomonie is willing to pay 0.5 dollars per ton for manure and
can take at most 500 tons.

A soybean farmer in Black River Falls is willing to pay 1.5 dollars per ton for
manure and can take at most 500 tons.

Transportation from Eau Claire to Menomonie costs 0.1 dollars per ton.
Transportation from Eau Claire to Black River Falls costs 0.2 dollars per ton.

The cooperative maximizes total profit. Determine the optimal manure allocation,
the total profit, and whether the dairy farmer can get rid of all 1000 tons of
manure.

            metric   value
0  objective_value   850.0
1   demand_revenue  1000.0
2   transport_cost   150.0
3      supply_cost     0.0

{'benchmark_id': 'midterm1_manure_q1',
 'objective_value': 850.0,
 'demand_revenue': 1000.0,
 'transport_cost': 150.0,
 'supply_cost': 0.0,
 'accepted_supply': {'Dairy/EauClaire': 1000.0},
 'accepted_demands': {'Menomonie': 500.0, 'BlackRiverFalls': 500.0},
 'transport_flows': {'EauClaire_to_Menomonie': 500.0,
  'EauClaire_to_BlackRiverFalls': 500.0},
 'route_net_values': {'EauClaire_to_Menomonie': 0.4,
  'EauClaire_to_BlackRiverFalls': 1.3},
 'balance_checks': {'EauClaire': {'supply': 1000.0,
   'total_outgoing_flow': 1000.0,
   'holds': True},
  'Menomonie': {'incoming_flow': 500.0,
   'accepted_demand': 500.0,
   'holds': True},
  'BlackRiverFalls': {'incoming_flow': 500.0,
   'accepted_demand': 500.0,
   'holds': True}},
 'qualitative_answer': 'The dairy farmer can get rid of all manure because total profitable demand capacity equals 1000 tons.'}

## Canonical And Paraphrased Prompt Runs

In [5]:
USE_LLM = bool(os.environ.get("GEMINI_API_KEY"))

config = MidtermBenchmarkConfig(
    prompt_ids=("canonical", "paraphrased"),
    use_llm=USE_LLM,
    use_llm_for_reasoning=USE_LLM,
    fallback_to_reference_fixture=True,
    attempt_solve=True,
    run_reasoning=False,
)
report = run_midterm_manure_q1_benchmark(config=config)

display(pd.DataFrame([report["metadata"]]))
display(report["tables"]["case_summary"])
display(report["tables"]["solve_accuracy"])
display(report["tables"]["interpretation_errors"])
display(report["tables"]["semantic_count_metrics"])
display(report["tables"]["parameter_multiset_metrics"])
display(report["tables"]["topology_metrics"])
display(report["tables"]["route_economics_metrics"])
display(report["tables"]["solver_aggregate_metrics"])
display(report["tables"]["balance_residual_metrics"])
display(report["tables"]["alias_resolution_diagnostics"])
display(report["tables"]["interpretation_metadata"])

,benchmark_id,benchmark_dir,llm_provider,gemini_model,gemini_configured,config
0,midterm1_manure_q1,/Users/mgomezochoa/Documents/ChatbotLP/Benchma...,gemini,gemini-3-flash-preview,True,"{'mode': 'guided', 'prompt_ids': ('canonical',..."

,prompt_id,label,semantic_plan_created,problem_state_created,structural_match,semantic_structure_pass,solver_aggregate_pass,balance_residual_pass,primary_success,alias_structural_match,...,solver_ready_expected,solver_ready_actual,solver_ready_correct,solve_success,objective_match,transport_flow_match,balance_match,explanation_generated,passed_checks,total_applicable_checks
0,canonical,Canonical midterm wording,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,False,7,7
1,paraphrased,Paraphrased complete wording,True,True,True,True,True,True,True,False,...,True,True,True,True,True,False,False,False,7,7

,prompt_id,solve_success,status,solver_name,expected_objective,actual_objective,objective_match,accepted_supply_match,accepted_demand_match,transport_flow_match,balance_match,demand_revenue_match,transport_cost_match,supply_cost_match,accepted_supply_total_match,solver_message
0,canonical,True,optimal,glpk,850.0,850.0,True,True,True,True,True,True,True,True,True,Solver glpk terminated with status optimal (te...
1,paraphrased,True,optimal,glpk,850.0,850.0,True,True,False,False,False,True,True,True,True,Solver glpk terminated with status optimal (te...

,prompt_id,structural_match,blocking_error_count,benign_extra_name_fields,benign_identifier_mismatches,blocking_error_categories,blocking_errors,missing_parameters,invalid_references
0,canonical,True,0,10,10,,,,
1,paraphrased,False,8,7,7,"extra_invented_entity, extra_invented_entity, ...",missing_entity at nodes.node:Menomonie; extra_...,,

     prompt_id                    metric  expected  actual  pass details
0    canonical                  products         1       1  True    None
1    canonical  source_supplier_entities         1       1  True    None
2    canonical  demand_consumer_entities         2       2  True    None
3    canonical           transport_paths         2       2  True    None
4    canonical              technologies         0       0  True    None
5  paraphrased                  products         1       1  True    None
6  paraphrased  source_supplier_entities         1       1  True    None
7  paraphrased  demand_consumer_entities         2       2  True    None
8  paraphrased           transport_paths         2       2  True    None
9  paraphrased              technologies         0       0  True    None

,prompt_id,metric,expected,actual,pass,details
0,canonical,supplier_capacities,[1000.0],[1000.0],True,NaN
1,canonical,consumer_capacities,"[500.0, 500.0]","[500.0, 500.0]",True,NaN
2,canonical,consumer_bid_prices,"[0.5, 1.5]","[0.5, 1.5]",True,NaN
3,canonical,supplier_bid_prices,[0.0],[0.0],True,NaN
4,canonical,transport_costs,"[0.1, 0.2]","[0.1, 0.2]",True,NaN
5,canonical,transport_capacities,"absent/unbounded with successful solve, or [50...",absent/unbounded,True,Transport capacities may be absent when routes...
6,paraphrased,supplier_capacities,[1000.0],[1000.0],True,NaN
7,paraphrased,consumer_capacities,"[500.0, 500.0]","[500.0, 500.0]",True,NaN
8,paraphrased,consumer_bid_prices,"[0.5, 1.5]","[0.5, 1.5]",True,NaN
9,paraphrased,supplier_bid_prices,[0.0],[0.0],True,NaN
10,paraphrased,transport_costs,"[0.1, 0.2]","[0.1, 0.2]",True,NaN
11,paraphrased,transport_capacities,"absent/unbounded with successful solve, or [50...",absent/unbounded,True,Transport capacities may be absent when routes...

,prompt_id,metric,expected,actual,pass,details
0,canonical,one_source_node,True,True,True,"[""Eau Claire""]"
1,canonical,two_distinct_sink_nodes,True,True,True,"[""Black River Falls"", ""Menomonie""]"
2,canonical,source_outgoing_to_two_sinks,True,True,True,"{""destinations"": [""Black River Falls"", ""Menomo..."
3,canonical,no_technologies,True,True,True,NaN
4,canonical,no_negative_bids,True,True,True,"[0.0, 0.5, 1.5]"
5,canonical,all_transport_arcs_carry_manure,True,True,True,"[""Manure"", ""Manure""]"
6,paraphrased,one_source_node,True,True,True,"[""EC""]"
7,paraphrased,two_distinct_sink_nodes,True,True,True,"[""BRF"", ""MEN""]"
8,paraphrased,source_outgoing_to_two_sinks,True,True,True,"{""destinations"": [""BRF"", ""MEN""], ""source"": ""EC""}"
9,paraphrased,no_technologies,True,True,True,NaN
10,paraphrased,no_negative_bids,True,True,True,"[0.0, 0.5, 1.5]"
11,paraphrased,all_transport_arcs_carry_manure,True,True,True,"[""Manure"", ""Manure""]"

,prompt_id,metric,expected,actual,pass,details
0,canonical,sorted_route_net_values,"[0.4, 1.3]","[0.4, 1.3]",True,consumer willingness-to-pay - transport cost -...
1,paraphrased,sorted_route_net_values,"[0.4, 1.3]","[0.4, 1.3]",True,consumer willingness-to-pay - transport cost -...

,prompt_id,metric,expected,actual,pass,details
0,canonical,objective_value,850.0,850.0,True,None
1,canonical,demand_revenue,1000.0,1000.0,True,None
2,canonical,transport_cost,150.0,150.0,True,None
3,canonical,supply_cost,0.0,0.0,True,None
4,canonical,total_accepted_supply,1000.0,1000.0,True,None
5,canonical,total_accepted_demand,1000.0,1000.0,True,None
6,canonical,total_transport_flow,1000.0,1000.0,True,None
7,canonical,active_transport_routes,2,2,True,None
8,canonical,sorted_active_flow_values,"[500.0, 500.0]","[500.0, 500.0]",True,None
9,canonical,sorted_accepted_demand_values,"[500.0, 500.0]","[500.0, 500.0]",True,None
10,paraphrased,objective_value,850.0,850.0,True,None
11,paraphrased,demand_revenue,1000.0,1000.0,True,None
12,paraphrased,transport_cost,150.0,150.0,True,None
13,paraphrased,supply_cost,0.0,0.0,True,None
14,paraphrased,total_accepted_supply,1000.0,1000.0,True,None
15,paraphrased,total_accepted_demand,1000.0,1000.0,True,None
16,paraphrased,total_transport_flow,1000.0,1000.0,True,None
17,paraphrased,active_transport_routes,2,2,True,None
18,paraphrased,sorted_active_flow_values,"[500.0, 500.0]","[500.0, 500.0]",True,None
19,paraphrased,sorted_accepted_demand_values,"[500.0, 500.0]","[500.0, 500.0]",True,None

,prompt_id,metric,expected,actual,pass,details
0,canonical,max_abs_balance_residual,<= 1e-06,0.0,True,"{""Black River Falls:Manure"": 0.0, ""Eau Claire:..."
1,canonical,sum_abs_balance_residual,<= 1e-06,0.0,True,NaN
2,canonical,balance_violation_count,0,0.0,True,NaN
3,paraphrased,max_abs_balance_residual,<= 1e-06,0.0,True,"{""BRF:Manure"": 0.0, ""EC:Manure"": 0.0, ""MEN:Man..."
4,paraphrased,sum_abs_balance_residual,<= 1e-06,0.0,True,NaN
5,paraphrased,balance_violation_count,0,0.0,True,NaN

,prompt_id,component,raw_interpreted_ids,raw_bid_ids,raw_nodes,raw_origin,raw_destination,raw_product,canonical_resolved_id,reference_id,actual_value,expected_value,numeric_match
0,canonical,accepted_supply,S1,B1,Eau Claire,NaN,NaN,Manure,Dairy/EauClaire,Dairy/EauClaire,1000.0,1000.0,True
1,canonical,accepted_demands,C2,B3,Black River Falls,NaN,NaN,Manure,BlackRiverFalls,BlackRiverFalls,500.0,500.0,True
2,canonical,accepted_demands,C1,B2,Menomonie,NaN,NaN,Manure,Menomonie,Menomonie,500.0,500.0,True
3,canonical,transport_flows,T2,NaN,NaN,Eau Claire,Black River Falls,Manure,EauClaire_to_BlackRiverFalls,EauClaire_to_BlackRiverFalls,500.0,500.0,True
4,canonical,transport_flows,T1,NaN,NaN,Eau Claire,Menomonie,Manure,EauClaire_to_Menomonie,EauClaire_to_Menomonie,500.0,500.0,True
5,canonical,balance_checks,NaN,NaN,BlackRiverFalls,NaN,NaN,Manure,BlackRiverFalls,BlackRiverFalls,"{""accepted_demand"": 500.0, ""holds"": true, ""inc...","{""accepted_demand"": 500.0, ""holds"": true, ""inc...",True
6,canonical,balance_checks,NaN,NaN,EauClaire,NaN,NaN,Manure,EauClaire,EauClaire,"{""holds"": true, ""supply"": 1000.0, ""total_outgo...","{""holds"": true, ""supply"": 1000.0, ""total_outgo...",True
7,canonical,balance_checks,NaN,NaN,Menomonie,NaN,NaN,Manure,Menomonie,Menomonie,"{""accepted_demand"": 500.0, ""holds"": true, ""inc...","{""accepted_demand"": 500.0, ""holds"": true, ""inc...",True
8,paraphrased,accepted_supply,S_EC,B_S_EC,EC,NaN,NaN,Manure,Dairy/EauClaire,Dairy/EauClaire,1000.0,1000.0,True
9,paraphrased,accepted_demands,C_BRF,B_C_BRF,BRF,NaN,NaN,Manure,BlackRiverFalls,BlackRiverFalls,500.0,500.0,True
10,paraphrased,accepted_demands,C_MEN,B_C_MEN,MEN,NaN,NaN,Manure,C_MEN,NaN,500.0,None,False
11,paraphrased,accepted_demands,NaN,NaN,NaN,NaN,NaN,NaN,Menomonie,Menomonie,0.0,500.0,False
12,paraphrased,transport_flows,T_EC_BRF,NaN,NaN,EC,BRF,Manure,EauClaire_to_BlackRiverFalls,EauClaire_to_BlackRiverFalls,500.0,500.0,True
13,paraphrased,transport_flows,T_EC_MEN,NaN,NaN,EC,MEN,Manure,EauClaire_to_MEN,NaN,500.0,None,False
14,paraphrased,transport_flows,NaN,NaN,NaN,NaN,NaN,NaN,EauClaire_to_Menomonie,EauClaire_to_Menomonie,0.0,500.0,False
15,paraphrased,balance_checks,NaN,NaN,BlackRiverFalls,NaN,NaN,Manure,BlackRiverFalls,BlackRiverFalls,"{""accepted_demand"": 500.0, ""holds"": true, ""inc...","{""accepted_demand"": 500.0, ""holds"": true, ""inc...",True
16,paraphrased,balance_checks,NaN,NaN,EauClaire,NaN,NaN,Manure,EauClaire,EauClaire,"{""holds"": false, ""supply"": 1000.0, ""total_outg...","{""holds"": true, ""supply"": 1000.0, ""total_outgo...",False
17,paraphrased,balance_checks,NaN,NaN,Menomonie,NaN,NaN,Manure,Menomonie,Menomonie,"{""accepted_demand"": 0.0, ""holds"": true, ""incom...","{""accepted_demand"": 500.0, ""holds"": true, ""inc...",False

,prompt_id,interpretation_source,fallback_used,fallback_reason,llm_failure,llm_provider,gemini_model
0,canonical,live_llm_pipeline,False,None,None,gemini,gemini-3-flash-preview
1,paraphrased,live_llm_pipeline,False,None,None,gemini,gemini-3-flash-preview

In [6]:
canonical_case = report["cases"][0]
display(canonical_case["validation_result"])
display(canonical_case["solution_checks"]["actual_components"])

{'issues': [],
 'missing_parameters': [],
 'invalid_references': [],
 'incomplete_technologies': [],
 'solver_ready': True,
 'benchmark_compatibility': {'Case A': {'compatible': True,
   'explanation': 'no technologies present'},
  'Case B': {'compatible': False, 'explanation': 'no negative bids found'},
  'Case C': {'compatible': False,
   'explanation': 'no technology with both input (neg) and output (pos) yields found'}}}

{'accepted_supply': {'Dairy/EauClaire': 1000.0},
 'accepted_demands': {'Menomonie': 500.0, 'BlackRiverFalls': 500.0},
 'transport_flows': {'EauClaire_to_Menomonie': 500.0,
  'EauClaire_to_BlackRiverFalls': 500.0},
 'demand_revenue': 1000.0,
 'transport_cost': 150.0,
 'supply_cost': 0.0,
 'balance_checks': {'EauClaire': {'supply': 1000.0,
   'total_outgoing_flow': 1000.0,
   'holds': True},
  'Menomonie': {'incoming_flow': 500.0,
   'accepted_demand': 500.0,
   'holds': True},
  'BlackRiverFalls': {'incoming_flow': 500.0,
   'accepted_demand': 500.0,
   'holds': True}},
 'raw_component_rows': [{'component': 'accepted_supply',
   'raw_id': 'S1',
   'raw_bid_id': 'B1',
   'raw_node': 'Eau Claire',
   'raw_product': 'Manure',
   'canonical_resolved_id': 'Dairy/EauClaire',
   'actual_value': 1000.0},
  {'component': 'accepted_demands',
   'raw_id': 'C1',
   'raw_bid_id': 'B2',
   'raw_node': 'Menomonie',
   'raw_product': 'Manure',
   'canonical_resolved_id': 'Menomonie',
   'actual_value': 500.0},
  {'component': 'accepted_demands',
   'raw_id': 'C2',
   'raw_bid_id': 'B3',
   'raw_node': 'Black River Falls',
   'raw_product': 'Manure',
   'canonical_resolved_id': 'BlackRiverFalls',
   'actual_value': 500.0},
  {'component': 'transport_flows',
   'raw_id': 'T1',
   'raw_arc': "('Eau Claire', 'Menomonie')",
   'raw_origin': 'Eau Claire',
   'raw_destination': 'Menomonie',
   'raw_product': 'Manure',
   'canonical_resolved_id': 'EauClaire_to_Menomonie',
   'actual_value': 500.0},
  {'component': 'transport_flows',
   'raw_id': 'T2',
   'raw_arc': "('Eau Claire', 'Black River Falls')",
   'raw_origin': 'Eau Claire',
   'raw_destination': 'Black River Falls',
   'raw_product': 'Manure',
   'canonical_resolved_id': 'EauClaire_to_BlackRiverFalls',
   'actual_value': 500.0}]}

## Required Reasoning Prompts

In [7]:
reasoning_config = MidtermBenchmarkConfig(
    prompt_ids=("canonical",),
    use_llm=USE_LLM,
    use_llm_for_reasoning=USE_LLM,
    fallback_to_reference_fixture=True,
    attempt_solve=True,
    run_reasoning=True,
)
reasoning_report = run_midterm_manure_q1_benchmark(config=reasoning_config)
display(reasoning_report["tables"]["reasoning_prompt_success"])

for row in reasoning_report["cases"][0]["reasoning_results"]:
    display(Markdown(f"### {row['prompt_label']}\n\n{row['response_preview']}"))

,case,prompt_id,prompt_label,success,required_terms,required_terms_present,intent,render_mode,response_source,fallback_triggered,fallback_reason,llm_exception_type,response_preview
0,canonical,primal_lp,Primal LP formulation,True,,None,formal_math,markdown_latex,llm,False,NaN,NaN,"In the framework of Sampat et al. (2019), manu..."
1,canonical,economic_intuition,Economic intuition,False,,None,explanation,NaN,deterministic,True,llm_exception,RuntimeError,Intuition: the current coordinated clearing mo...
2,canonical,all_manure,All manure feasibility,True,,None,explanation,NaN,llm,False,NaN,NaN,Based on the current problem state for the **D...
3,canonical,node_balances,Node balance verification,False,,None,validation,NaN,deterministic,True,llm_exception,RuntimeError,Guided Response:\nProblem: Dairy Manure Alloca...

### Primal LP formulation

In the framework of Sampat et al. (2019), manure management is modeled as a coordinated clearing problem. The system acts as a central coordinator that maximizes the total surplus of the network—interpreted as the aggregate benefit to consu

### Economic intuition

Intuition: the current coordinated clearing model links bids, flows, and technologies through node-product balance conditions.
Mathematical interpretation: the current state has 3 node(s), 1 product(s), and 3 bid(s), so any explanation shou

### All manure feasibility

Based on the current problem state for the **Dairy Manure Allocation Optimization**, here is the guided explanation regarding the farmer's ability to dispose of the manure.

### Intuition
Think of this as a balancing act between a source an

### Node balance verification

Guided Response:
Problem: Dairy Manure Allocation Optimization
Entities: 3 nodes, 1 products, 1 suppliers, 2 consumers.
The model is ready to solve.

## Flow Table

In [ ]:
flow_table = pd.DataFrame([
    {"route": "Eau Claire -> Menomonie", "flow_tons": 500},
    {"route": "Eau Claire -> Black River Falls", "flow_tons": 500},
])
display(flow_table)

## Paper-Style Summary Export

In [ ]:
output_dir = REPO_ROOT / "midterm_outputs"
write_midterm_outputs(report, output_dir)
reasoning_report["tables"]["reasoning_prompt_success"].to_csv(
    output_dir / "reasoning_prompt_success_canonical.csv",
    index=False,
)
flow_table.to_csv(output_dir / "manure_q1_flow_table.csv", index=False)

paper_summary = report["tables"]["case_summary"][[
    "prompt_id",
    "solver_ready_actual",
    "semantic_structure_pass",
    "solver_aggregate_pass",
    "balance_residual_pass",
    "primary_success",
    "solve_success",
]]
paper_summary.to_csv(output_dir / "paper_style_summary.csv", index=False)
display(paper_summary)
output_dir