# Prose-to-Reasoning Regression Demo

This local VS Code / Mac notebook verifies that the natural-prose path preserves the original coordinated supply chain framework capabilities for Case A.

Pipeline demonstrated: natural prose -> semantic plan -> `ProblemState` -> validate -> solve -> reason/explain.

In [1]:
import os

os.environ["GEMINI_API_KEY"] = "AIzaSyAXIzI5oLE66pAIuY0ErNI3z3L_cLWne90"
os.environ["LLM_PROVIDER"] = "gemini"
os.environ["GEMINI_MODEL"] = "gemini-3-flash-preview"

Paste your Gemini API key in the cell above, then run the notebook top to bottom. The notebook reuses repo modules rather than redefining architecture or moving logic into notebook cells.

In [2]:
import json
import sys
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display

REPO_ROOT = Path.cwd()
if not (REPO_ROOT / "src").exists():
    REPO_ROOT = REPO_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.llm_problem_interpreter import interpret_problem_from_text, summarize_problem_state
from src.prose_interpreter_evaluation import build_benchmark_evaluation_cases, compare_problem_states
from src.validator import validate_state
from src.model_builder import build_market_instance, build_model_from_market_instance
from src.solver import solve_model
from src.solver_results import SolverResults
from src.theorem_checker import check_theorems
from src.response_generator import generate_response_with_metadata
from src.chatbot_engine import ask_chatbot

REPO_ROOT

PosixPath('/Users/mgomezochoa/Documents/ChatbotLP')

## Case A Natural-Prose Input

This is the Case A, no-transformation benchmark description used for the regression check.

In [3]:
case_a = next(case for case in build_benchmark_evaluation_cases() if case["name"] == "canonical_case_a")
case_a_prose = case_a["prose"]
manual_case_a_state = case_a["expected_state"]

display(Markdown(case_a_prose))

There are two nodes, N1 and N2. Supplier S1 at N1 can supply up to 100 units of product P1. Consumer C1 at N2 is willing to buy up to 50 units of P1 at price 20. Supplier S1 offers P1 at price 10. A transport link T1 carries P1 from N1 to N2 with capacity 100.

## Natural Prose -> Semantic Plan -> ProblemState

`interpret_problem_from_text` is the existing repo entry point for the prose layer. It calls Gemini to produce a semantic plan, normalizes that plan, builds a `ProblemState`, and creates the downstream machine-facing market instance.

In [4]:
if not os.environ.get("GEMINI_API_KEY"):
    raise RuntimeError("Paste your Gemini key into the setup cell before running the live prose regression.")

artifacts = interpret_problem_from_text(case_a_prose)

semantic_plan = artifacts["semantic_plan"]
prose_state = artifacts["problem_state"]
prose_market_instance = artifacts["market_instance"]

display(Markdown("### Semantic Plan"))
print(json.dumps(semantic_plan, indent=2))

display(Markdown("### ProblemState Summary"))
print(json.dumps(summarize_problem_state(prose_state), indent=2))

### Semantic Plan

{
  "problem_title": "Product P1 Supply from N1 to N2",
  "problem_type": "case_a",
  "nodes": [
    {
      "id": "N1"
    },
    {
      "id": "N2"
    }
  ],
  "products": [
    {
      "id": "P1"
    }
  ],
  "suppliers": [
    {
      "id": "S1",
      "node": "N1",
      "product": "P1",
      "capacity": 100.0
    }
  ],
  "consumers": [
    {
      "id": "C1",
      "node": "N2",
      "product": "P1",
      "capacity": 50.0
    }
  ],
  "transport_links": [
    {
      "id": "T1",
      "origin": "N1",
      "destination": "N2",
      "product": "P1",
      "capacity": 100.0,
      "cost": null
    }
  ],
  "bids": [
    {
      "id": "B1",
      "owner_id": "S1",
      "owner_type": "supplier",
      "product_id": "P1",
      "price": 10.0,
      "quantity": 100.0
    },
    {
      "id": "B2",
      "owner_id": "C1",
      "owner_type": "consumer",
      "product_id": "P1",
      "price": 20.0,
      "quantity": 50.0
    }
  ],
  "technologies": [],
  "missing_information": [
    "transport cost for T1"
  ],
  "ambiguities": []
}

### ProblemState Summary

{
  "problem_title": "Product P1 Supply from N1 to N2",
  "counts": {
    "nodes": 2,
    "products": 1,
    "suppliers": 1,
    "consumers": 1,
    "transport_links": 1,
    "bids": 2,
    "technologies": 0
  },
  "node_ids": [
    "N1",
    "N2"
  ],
  "product_ids": [
    "P1"
  ]
}

## Regression Check Against Manual ProblemState

The historical path started from a manually constructed `ProblemState`. This cell compares the interpreted state against the existing expected Case A state from the repo's prose evaluation helper.

In [5]:
comparison = compare_problem_states(manual_case_a_state, prose_state)

# The LLM may preserve optional human-readable names such as nodes.N1.name or
# products.P1.name. Those are benign extras because they do not alter the
# mathematical Case A structure or downstream model-building behavior.
benign_extra_fields = [
    field
    for field in comparison["extra_fields"]
    if field.get("path", "").startswith(("nodes.", "products."))
    and field.get("path", "").endswith(".name")
]
blocking_extra_fields = [
    field
    for field in comparison["extra_fields"]
    if field not in benign_extra_fields
]

summary_rows = [
    {"category": "passed_fields", "count": len(comparison["passed_fields"])},
    {"category": "failed_fields", "count": len(comparison["failed_fields"])},
    {"category": "missing_fields", "count": len(comparison["missing_fields"])},
    {"category": "benign_extra_name_fields", "count": len(benign_extra_fields)},
    {"category": "blocking_extra_fields", "count": len(blocking_extra_fields)},
]
display(pd.DataFrame(summary_rows))

if comparison["failed_fields"] or comparison["missing_fields"] or blocking_extra_fields:
    print(json.dumps({
        "failed_fields": comparison["failed_fields"],
        "missing_fields": comparison["missing_fields"],
        "blocking_extra_fields": blocking_extra_fields,
        "error_category_counts": comparison["error_category_counts"],
    }, indent=2))

if benign_extra_fields:
    display(Markdown("### Benign optional name fields retained by prose interpretation"))
    print(json.dumps(benign_extra_fields, indent=2))

assert not comparison["failed_fields"], "Interpreted state has field mismatches versus manual Case A state."
assert not comparison["missing_fields"], "Interpreted state is missing fields from manual Case A state."
assert not blocking_extra_fields, "Interpreted state has structural extra fields versus manual Case A state."

                   category  count
0             passed_fields     23
1             failed_fields      0
2            missing_fields      0
3  benign_extra_name_fields      0
4     blocking_extra_fields      0

## Validate and Check Assumptions

Validation and theorem/assumption checks are deterministic repo functions applied to the interpreted `ProblemState`.

In [6]:
validation_result = validate_state(prose_state)
theorem_checks = check_theorems(prose_state)

display(Markdown("### Validation"))
print(json.dumps(validation_result, indent=2))

display(Markdown("### Theorem / Benchmark Checks"))
display(pd.DataFrame([
    {
        "theorem_id": check.theorem_id,
        "theorem_name": check.theorem_name,
        "applies": check.applies,
        "explanation": check.explanation,
    }
    for check in theorem_checks
]))

assert validation_result["solver_ready"], "Case A prose interpretation should be solver-ready."
assert validation_result["benchmark_compatibility"]["Case A"]["compatible"], "Case A compatibility should be preserved."
assert not prose_state.technologies, "Case A should not contain transformation technologies."

### Validation

{
  "issues": [],
  "missing_parameters": [],
  "invalid_references": [],
  "incomplete_technologies": [],
  "solver_ready": true,
  "benchmark_compatibility": {
    "Case A": {
      "compatible": true,
      "explanation": "no technologies present"
    },
    "Case B": {
      "compatible": false,
      "explanation": "no negative bids found"
    },
    "Case C": {
      "compatible": false,
      "explanation": "no technology with both input (neg) and output (pos) yields found"
    }
  }
}

### Theorem / Benchmark Checks

,theorem_id,theorem_name,applies,explanation
0,basic_supply_demand_structure,Basic supply-demand structure,True,At least one supply-side and one demand-side e...
1,case_a_compatibility,Case A compatibility (no transformation),True,no technologies present
2,case_b_compatibility,Case B compatibility (negative bidding),False,no negative bids found
3,case_c_compatibility,Case C compatibility (transformation),False,no technology with both input (neg) and output...
4,theorem_1,Theorem 1 applicability,True,validated linear structure supports the scoped...

## Solve Interpreted and Manual States

Both paths use the same model builder and solver wrapper. If no local Pyomo-compatible LP solver is available, the result is reported as solver-unavailable rather than pretending a solve occurred.

In [7]:
def solve_state(state):
    market_instance = build_market_instance(state)
    model = build_model_from_market_instance(market_instance)
    raw_result = solve_model(model, solver_name="glpk", fallback_solver="ipopt")
    return raw_result, raw_result.to_dict(), SolverResults.from_solve_result(raw_result, state)

prose_raw_solve, prose_solve_result, prose_solver_results = solve_state(prose_state)
manual_raw_solve, manual_solve_result, manual_solver_results = solve_state(manual_case_a_state)

display(pd.DataFrame([
    {
        "path": "natural prose -> ProblemState",
        "success": prose_solve_result["success"],
        "status": prose_solve_result["status"],
        "termination": prose_solve_result["termination_condition"],
        "solver": prose_solve_result["solver_name"],
        "objective": prose_solve_result["objective_value"],
    },
    {
        "path": "manual ProblemState",
        "success": manual_solve_result["success"],
        "status": manual_solve_result["status"],
        "termination": manual_solve_result["termination_condition"],
        "solver": manual_solve_result["solver_name"],
        "objective": manual_solve_result["objective_value"],
    },
]))

if prose_solve_result["success"] and manual_solve_result["success"]:
    assert abs(prose_solve_result["objective_value"] - manual_solve_result["objective_value"]) <= 1e-8
else:
    print("At least one solve did not succeed. This is usually solver availability; inspect the messages below.")
    print("Prose solve:", prose_solve_result["message"])
    print("Manual solve:", manual_solve_result["message"])

,path,success,status,termination,solver,objective
0,natural prose -> ProblemState,True,optimal,optimal,glpk,500.0
1,manual ProblemState,True,optimal,optimal,glpk,500.0

## Case A — formulation, duality, theorem tests using prose-derived ProblemState

This prompt battery reproduces the original Case A formulation, duality, theorem, and interpretation checks, but uses `prose_state`, the `ProblemState` obtained from the natural-prose interpretation layer.

In [8]:
prompts_case_A = [
    "Formulate the current coordinated clearing problem as the primal linear program in LaTeX.",
    "Formulate the current coordinated clearing problem as the dual linear program in LaTeX.",
    "State Theorem 1 and prove it in LaTeX for the current coordinated clearing problem.",
    "Does strong duality hold for the current coordinated clearing problem? Give a brief explanation and then provide the proof in LaTeX.",
    "Explain the economic meaning of the dual variables in the current coordinated clearing problem.",
    "Explain the meaning of the node-product prices \\(\\pi_{np}\\) in the current coordinated clearing problem.",
    "Verify the complementary slackness conditions for the current primal-dual pair and explain their economic interpretation.",
]

results_case_A_from_prose = []
for p in prompts_case_A:
    result = ask_chatbot(prose_state, p, use_llm=True, mode="full")
    results_case_A_from_prose.append(result)

    display(Markdown(f"### Prompt\n`{p}`"))
    display(Markdown("### Response"))
    display(Markdown(result.get("response", result.get("answer", ""))))
    display(Markdown("### Metadata"))
    print(json.dumps({
        "intent": result.get("intent"),
        "success": result.get("success"),
        "response_metadata": result.get("response_metadata"),
    }, indent=2, default=str))
    print("-" * 100)

### Prompt
`Formulate the current coordinated clearing problem as the primal linear program in LaTeX.`

### Response

This exposition details the primal formulation of the coordinated clearing problem, grounded in the framework of Sampat et al. (2019). We interpret the clearing process through three layers: the intuition of the coordinated manager, the formal mathematical structure, and the economic implications of the primal variables and coefficients.

### 1. Intuition
In the coordinated management interpretation, the clearinghouse does not simply match buyers and sellers; it acts as a centralized manager optimizing the movement and transformation of commodities across a network. The goal is to maximize the **coordinated surplus**—the total value generated by consumption minus the costs of production and transportation. Here, we look at a specific instance involving two nodes ($N1, N2$) and one product ($P1$). The manager must decide how much of the product to accept from a supplier at $N1$, how much to move across the link to $N2$, and how much to satisfy a consumer at $N2$, staying within the physical and contractual limits of the system.

### 2. Mathematical Meaning
The problem is structured as a Linear Program (LP). The objective function aggregates the economic weights (bid prices and transport costs) associated with each activity. The constraints represent the physical conservation of mass (node-product balances) and the capacity limits on bids and infrastructure. Specifically, the node-product balance ensures that for any node, the sum of local production and inflows must equal the sum of local consumption and outflows.

The primal problem is formulated as follows:
$$
\begin{aligned}
\text{maximize} \quad & Z = -10 q_{B1} + 20 q_{B2} - 0 f_{N1,N2} \\
\text{subject to} \quad & \\
\text{(Node N1, P1 Balance)} \quad & 1 q_{B1} - 1 f_{N1,N2} = 0 \\
\text{(Node N2, P1 Balance)} \quad & -1 q_{B2} + 1 f_{N1,N2} = 0 \\
\text{(Supplier Bid B1)} \quad & 0 \le q_{B1} \le 100 \\
\text{(Consumer Bid B2)} \quad & 0 \le q_{B2} \le 50 \\
\text{(Transport N1-N2)} \quad & 0 \le f_{N1,N2} \le 1 \\
\end{aligned}
$$
In this formulation:
*   $q_{B1}$ and $q_{B2}$ represent the accepted quantities for the supplier and consumer bids, respectively.
*   $f_{N1,N2}$ represents the transport flow from node $N1$ to node $N2$.
*   The coefficients $-10$ and $20$ represent the marginal value or cost associated with each unit of bid acceptance.
*   The coefficients $1$ and $-1$ in the balance equations ensure the directional flow and consumption/supply logic are preserved.

### 3. Economic Interpretation
Following the logic of Sampat et al. (2019) Section 2.3, the coefficients in the objective function reveal the system's valuation.

*   **Negative Bids:** The coefficient $-10$ for $q_{B1}$ indicates that accepting a unit from supplier $B1$ reduces the total surplus. In the context of coordinated clearing, if a supplier bid is negative, it implies a cost to the system or a situation where the system must be compensated to take the product (e.g., waste remediation or disposal).
*   **Surplus Maximization:** The consumer bid $B2$ at node $N2$ has a high value ($20$), creating an incentive to move product across the network. However, the system is constrained by the transport capacity $f_{N1,N2} \le 1$.
*   **Coordinated Clearing:** The "clearing" occurs where the primal variables reach an optimal balance. Even though there is a large supply ($100$) and a large demand ($50$), the bottleneck in transport ($1$) restricts the total activity.
*   **Technologies:** While the general Sampat framework uses technology activity levels ($x_k$) and yield coefficients to link different products (e.g., transforming $P1$ into $P2$), this specific instantiation focuses purely on the transport and exchange of a single product ($P1$).

This primal model provides the physical "plan" for the system. The corresponding shadow prices (dual values) for the node-product balances would represent the nodal prices ($\pi_{N1,P1}$ and $\pi_{N2,P1}$), reflecting the marginal value of the product at each location under these constraints.

This response may not be fully grounded in the deterministic model.
- Primal response should contain the primal label and objective.
- Primal response should include the constraint label s.t.

### Metadata

{
  "intent": "formal_math",
  "success": true,
  "response_metadata": {
    "response_source": "llm",
    "fallback_triggered": false,
    "raw_llm_output_present": true,
    "llm_output_length": 4044,
    "fallback_reason": null,
    "llm_exception_type": null,
    "grounding_warning_applied": true,
    "validation_warnings": [
      "Primal response should contain the primal label and objective.",
      "Primal response should include the constraint label s.t."
    ],
    "validation_fatal": [],
    "mode_used": "full",
    "grounding_mode": "model"
  }
}
----------------------------------------------------------------------------------------------------

### Prompt
`Formulate the current coordinated clearing problem as the dual linear program in LaTeX.`

### Response

### Dual Formulation of the Coordinated Clearing Problem

In the coordinated management framework of Sampat et al. (2019), the clearing of a market is not merely a matching of quantities but a simultaneous valuation of resources, transport infrastructure, and nodal commodities. The dual formulation shifts the perspective from the optimal flow of goods to the optimal allocation of "rents" and "shadow prices."

#### 1. Intuition
The dual problem represents the perspective of a system coordinator seeking to minimize the total "congestion and scarcity rent" assigned to the system's physical and economic limits. Instead of deciding how much of a product to move (the primal variables), we determine the value of having one more unit of capacity at a specific node or on a specific transport arc. The dual ensures that the nodal price of a product accurately reflects the costs of supply, the utility of consumption, and the scarcity of the transport network.

#### 2. Mathematical Meaning
The dual program is constructed by assigning a multiplier to each constraint in the primal surplus maximization problem. In this instance, we consider a single product $P1$ across two nodes $N1$ and $N2$.

**Objective:** Minimize the total value of the system's capacity limits.
**Constraints:** Ensure that for every activity (supplying, consuming, or transporting), the marginal benefit does not exceed the marginal cost plus the associated scarcity rent.

Given the primal parameters—a supplier bid $B1$ at node $N1$ (cost coefficient $-10$), a consumer bid $B2$ at node $N2$ (value coefficient $20$), and a transport arc from $N1$ to $N2$ (cost $0$)—the dual formulation is:
$$
\begin{aligned}
\min_{\mu, \nu, \tau, \pi} \quad & 100 \mu_{B1} + 50 \nu_{B2} + 100 \tau_{N1,N2} \\
\text{subject to} \quad & \\
(q_{B1}): \quad & \pi_{N1,P1} + \mu_{B1} \ge -10 \\
(q_{B2}): \quad & \nu_{B2} - \pi_{N2,P1} \ge 20 \\
(f_{N1,N2}): \quad & \tau_{N1,N2} - \pi_{N1,P1} + \pi_{N2,P1} \ge 0 \\
\text{and} \quad & \mu_{B1}, \nu_{B2}, \tau_{N1,N2} \ge 0 \\
& \pi_{N1,P1}, \pi_{N2,P1} \text{ are free}
\end{aligned}
$$
#### 3. Economic Interpretation
In the Sampat coordinated-clearing framework, the dual variables $\pi_{N,P}$ are interpreted as **nodal prices**.

*   **Nodal Prices ($\pi_{N1,P1}, \pi_{N2,P1}$):** These represent the marginal value of the product $P1$ at each node. Because they are associated with equality constraints (node-product balance), they are "free" variables. Following Section 2.3, a negative price indicates that the system is oversupplied or that the product is a "bad" (e.g., waste) where the system effectively pays for its removal or disposal.
*   **Supplier Scarcity Rent ($\mu_{B1}$):** If the supplier's cost $(-10)$ is significantly lower than the nodal price $\pi_{N1,P1}$, the bid is fully accepted. The difference is captured by $\mu_{B1}$, representing the value of having an additional unit of supply capacity at that price point.
*   **Consumer Scarcity Rent ($\nu_{B2}$):** This captures the "unmet utility" if the consumer's bid is capped at 50 units. If the nodal price $\pi_{N2,P1}$ is lower than the consumer's marginal value (20), $\nu_{B2}$ becomes positive.
*   **Transport Rent ($\tau_{N1,N2}$):** This is the classic "congestion rent." The constraint $\tau_{N1,N2} \ge \pi_{N1,P1} - \pi_{N2,P1}$ (with 0 transport cost) implies that the price difference between two nodes cannot exceed the shadow price of the transport capacity. If the price at $N2$ is much higher than at $N1$, the transport link will be saturated, and $\tau$ will represent the value of expanding that link.

Consistent with the coordinated management interpretation, the dual formulation ensures that the "price of transformation" (including transport and technological yield, though technologies are omitted in this specific instance) is fully accounted for in the spatial price equilibrium.

This response may not be fully grounded in the deterministic model.
- Dual response should introduce the dual formulation explicitly.
- Dual response should include a recognizable dual objective.

### Metadata

{
  "intent": "formal_math",
  "success": true,
  "response_metadata": {
    "response_source": "llm",
    "fallback_triggered": false,
    "raw_llm_output_present": true,
    "llm_output_length": 3902,
    "fallback_reason": null,
    "llm_exception_type": null,
    "grounding_warning_applied": true,
    "validation_warnings": [
      "Dual response should introduce the dual formulation explicitly.",
      "Dual response should include a recognizable dual objective."
    ],
    "validation_fatal": [],
    "mode_used": "full",
    "grounding_mode": "model"
  }
}
----------------------------------------------------------------------------------------------------

### Prompt
`State Theorem 1 and prove it in LaTeX for the current coordinated clearing problem.`

### Response

### Coordinated Clearing and Strong Duality

#### 1. Intuition
In the coordinated management framework of Sampat et al. (2019), the clearing engine acts as a central coordinator that maximizes the total surplus of the system. This surplus is the net value created by satisfying consumer demand, minus the costs of supply and transport. Theorem 1 (Strong Duality) asserts that this centralized maximization problem is mathematically equivalent to a decentralized cost-minimization problem focused on the valuation of scarce capacities. Essentially, the "coordinated surplus" achieved by the manager is exactly equal to the "total scarcity rent" of the system's constraints.

#### 2. Mathematical Meaning
Theorem 1 establishes that for the linear program defining the coordinated clearing, the optimal primal objective value $z_P^*$ (surplus) equals the optimal dual objective value $z_D^*$ (capacity valuation), provided a solution exists.

**The Primal Problem ($\mathcal{P}$)**
Maximize the coordinated surplus:
$$
z_P = -10 q_{B1} + 20 q_{B2} - 0 f_{N1,N2}
$$
Subject to:
$$
\begin{aligned}
\text{Node N1, P1 Balance:} & \quad q_{B1} - f_{N1,N2} = 0 & (\pi_{N1,P1}) \\
\text{Node N2, P1 Balance:} & \quad f_{N1,N2} - q_{B2} = 0 & (\pi_{N2,P1}) \\
\text{Supplier B1 Cap:} & \quad q_{B1} \le 100 & (\mu_{B1}) \\
\text{Consumer B2 Cap:} & \quad q_{B2} \le 50 & (\nu_{B2}) \\
\text{Transport Cap:} & \quad f_{N1,N2} \le 100 & (\tau_{N1,N2}) \\
\text{Non-negativity:} & \quad q_{B1}, q_{B2}, f_{N1,N2} \ge 0
\end{aligned}
$$
**The Dual Problem ($\mathcal{D}$)**
Minimize the total valuation of system capacities:
$$
z_D = 100 \mu_{B1} + 50 \nu_{B2} + 100 \tau_{N1,N2}
$$
Subject to the stationarity (marginal pricing) conditions:
$$
\begin{aligned}
\text{for } q_{B1}: & \quad \pi_{N1,P1} + \mu_{B1} \ge -10 \\
\text{for } q_{B2}: & \quad -\pi_{N2,P1} + \nu_{B2} \ge 20 \\
\text{for } f_{N1,N2}: & \quad -\pi_{N1,P1} + \pi_{N2,P1} + \tau_{N1,N2} \ge 0 \\
\text{Dual Bounds:} & \quad \mu_{B1}, \nu_{B2}, \tau_{N1,N2} \ge 0, \quad \pi_{N1,P1}, \pi_{N2,P1} \text{ free}
\end{aligned}
$$
**Theorem 1 (Strong Duality)**
If the primal problem $\mathcal{P}$ has an optimal solution $q^*, f^*$, then the dual problem $\mathcal{D}$ has an optimal solution $\pi^*, \mu^*, \nu^*, \tau^*$ such that $z_P^* = z_D^*$.

**Proof.**
The problem $\mathcal{P}$ is a linear program.
1. **Feasibility:** The primal is feasible. For instance, the trivial solution $q_{B1}=0, q_{B2}=0, f_{N1,N2}=0$ satisfies all balance and capacity constraints.
2. **Boundedness:** The primal objective is bounded from above because all decision variables are constrained by finite upper bounds ($100, 50, 100$). Since the objective is a linear combination of finite variables, $z_P < \infty$.
3. **Application of Fundamental Theorem of LP:** By the Duality Theorem of Linear Programming, if a linear program is feasible and bounded, an optimal solution exists for both the primal and the dual, and their objective values are equal.
4. **Lagrangian Construction:** Define the Lagrangian $L$:
$$
\begin{aligned}
L = & -10 q_{B1} + 20 q_{B2} - 0 f_{N1,N2} \\
& + \pi_{N1,P1}(0 - (q_{B1} - f_{N1,N2})) \\
& + \pi_{N2,P1}(0 - (f_{N1,N2} - q_{B2})) \\
& + \mu_{B1}(100 - q_{B1}) + \nu_{B2}(50 - q_{B2}) + \tau_{N1,N2}(100 - f_{N1,N2})
\end{aligned}
$$
The saddle-point property of the Lagrangian for convex programs (including LPs) ensures that at optimality, the primal objective (maximization over $q, f$) and the dual objective (minimization over $\pi, \mu, \nu, \tau$) coincide.
Thus, $z_P^* = z_D^*$.

#### 3. Economic Interpretation
In the context of Sampat et al. (2019), Strong Duality confirms that the **Coordinated Surplus** (the total net benefit generated by the system) is exactly exhausted by the payments to the scarce resources (the **Shadow Prices** of capacity).

*   **Negative Bids:** The supplier $B1$ has a bid of $-10$. Consistent with Section 2.3, a negative supplier bid suggests a "Value of Service" or a disposal incentive where the system is effectively "paid" to accept the product. This increases the surplus as $q_{B1}$ increases (modeled as $-(-10)q_{B1}$ in surplus terms, or here as a negative cost $-10q_{B1}$ in a maximization sense).
*   **Shadow Prices ($\pi$):** The nodal prices $\pi_{n,p}$ emerge as the marginal cost of satisfying an additional unit of demand at a node. Strong duality ensures these prices are consistent with the marginal valuations of the bids.
*   **Capacity Rents:** $\mu, \nu, \tau$ represent the economic rent of the supplier, consumer, and transport constraints. If a constraint is not binding (e.g., $q_{B1} < 100$), its dual $\mu_{B1}$ is $0$.

The equality $z_P^* = z_D^*$ implies that the clearing process is efficient: all value generated by the optimal dispatch is accounted for in the dual prices of the system's physical and economic limits.

This response may not be fully grounded in the deterministic model.
- Theorem 1 response should include clean primal and dual problem headings.

### Metadata

{
  "intent": "formal_math",
  "success": true,
  "response_metadata": {
    "response_source": "llm",
    "fallback_triggered": false,
    "raw_llm_output_present": true,
    "llm_output_length": 4872,
    "fallback_reason": null,
    "llm_exception_type": null,
    "grounding_warning_applied": true,
    "validation_warnings": [
      "Theorem 1 response should include clean primal and dual problem headings."
    ],
    "validation_fatal": [],
    "mode_used": "full",
    "grounding_mode": "theorem"
  }
}
----------------------------------------------------------------------------------------------------

### Prompt
`Does strong duality hold for the current coordinated clearing problem? Give a brief explanation and then provide the proof in LaTeX.`

### Response

Yes, strong duality holds for the current coordinated clearing problem. In the framework of Sampat et al. (2019), the clearing of markets with transport and technology constraints is formulated as a Linear Program (LP). Since the primal problem is feasible (e.g., zero flow/acceptance) and bounded by finite capacities, the Fundamental Theorem of Linear Programming guarantees that the primal and dual optimal objectives are identical, and no duality gap exists.

### Contextual Explanation

1.  **Intuition**
    In a coordinated system, the "best" way to move and transform products to maximize surplus is exactly balanced by the "value" of the constraints holding the system back. Strong duality implies that every unit of economic surplus generated by the clearing engine can be perfectly decomposed into the shadow prices of the resources (nodes, transport arcs, and bids) that made that surplus possible.

2.  **Mathematical Meaning**
    The problem is an instantiated Linear Program. For any LP, if a feasible solution exists and the objective function is bounded within the feasible region, the dual problem is also feasible and bounded. The Strong Duality Theorem states that at optimality, the maximum value of the primal objective (Coordinated Surplus) equals the minimum value of the dual objective (the sum of capacity-weighted scarcity rents).

3.  **Economic Interpretation**
    In the Sampat coordinated-clearing framework, strong duality ensures "exhaustion of surplus." The total system benefit—calculated as consumer value minus supplier costs and transport/technology expenses—is fully distributed as nodal prices ($\pi_{n,p}$) and capacity rents ($\mu, \nu, \tau$). Even if bids or prices are negative (consistent with Section 2.3 for disposal or remediation), the duality relationship ensures that the system's willingness to pay for a service is equal to the marginal cost of providing it, including the cost of overcoming binding bottlenecks.

***

### Proof of Strong Duality

Let the primal problem be defined by the maximization of the Coordinated Surplus $Z_P$ with respect to acceptance quantities $q$ and flows $f$.

**1. Primal Formulation (P):**
$$
\begin{aligned}
\max_{q, f \ge 0} \quad & Z_P = -10 q_{B1} + 20 q_{B2} - 0 f_{N1,N2} \\
\text{s.t.} \quad & \pi_{N1,P1}: \quad q_{B1} - f_{N1,N2} = 0 \\
& \pi_{N2,P1}: \quad f_{N1,N2} - q_{B2} = 0 \\
& \mu_{B1}: \quad q_{B1} \le 100 \\
& \nu_{B2}: \quad q_{B2} \le 50 \\
& \tau_{N1,N2}: \quad f_{N1,N2} \le 100
\end{aligned}
$$
**2. Existence of Feasible Solutions:**
The primal problem (P) is non-empty. The trivial solution $q_{B1} = 0, q_{B2} = 0, f_{N1,N2} = 0$ satisfies all node-product balance equalities and capacity inequalities. Thus, the primal is **feasible**.

**3. Boundedness:**
The objective function is a linear combination of variables $q_{B1}, q_{B2}, f_{N1,N2}$. Since the feasible set is a closed and bounded polytope (defined by $0 \le q_{B1} \le 100$, $0 \le q_{B2} \le 50$, and $0 \le f_{N1,N2} \le 100$), the objective function $Z_P$ cannot tend toward infinity. Thus, the primal is **bounded**.

**4. Strong Duality Theorem for LP:**
According to the Strong Duality Theorem, if a linear programming problem has an optimal solution, then its dual also has an optimal solution, and the two objective values are equal. Given feasibility and boundedness, an optimal solution $(q^*, f^*)$ exists.

**5. Dual Stationarity (Optimality Conditions):**
The Lagrangian $L$ for this system incorporates the dual variables $\mu_{B1}, \nu_{B2}, \tau_{N1,N2} \ge 0$ and free multipliers $\pi_{N1,P1}, \pi_{N2,P1}$:
$$
\begin{aligned}
L = & -10 q_{B1} + 20 q_{B2} - 0 f_{N1,N2} \\
& + \pi_{N1,P1}(f_{N1,N2} - q_{B1}) \\
& + \pi_{N2,P1}(q_{B2} - f_{N1,N2}) \\
& + \mu_{B1}(100 - q_{B1}) + \nu_{B2}(50 - q_{B2}) + \tau_{N1,N2}(100 - f_{N1,N2})
\end{aligned}
$$
At the optimum, the Karush-Kuhn-Tucker (KKT) conditions are satisfied. Because the problem is linear, the KKT conditions are both necessary and sufficient. The equality of the primal objective $Z_P$ and the dual objective $Z_D$ (the minimum capacity-weighted costs) is guaranteed:
$$
Z_P^* = Z_D^* = 100 \mu_{B1}^* + 50 \nu_{B2}^* + 100 \tau_{N1,N2}^*
$$
This concludes the proof that strong duality holds for the coordinated clearing problem.

### Metadata

{
  "intent": "formal_math",
  "success": true,
  "response_metadata": {
    "response_source": "llm",
    "fallback_triggered": false,
    "raw_llm_output_present": true,
    "llm_output_length": 4296,
    "fallback_reason": null,
    "llm_exception_type": null,
    "grounding_warning_applied": false,
    "validation_warnings": [],
    "validation_fatal": [],
    "mode_used": "full",
    "grounding_mode": "paper"
  }
}
----------------------------------------------------------------------------------------------------

### Prompt
`Explain the economic meaning of the dual variables in the current coordinated clearing problem.`

### Response

In the coordinated clearing framework of Sampat et al. (2019), the dual variables (or shadow values) represent the marginal sensitivities of the system-wide coordinated surplus. They provide the signals necessary to decentralize the clearing decision while maintaining the "coordinated management" objective—ensuring that localized bid acceptance and transport flows align with the global optimum.

The following exposition details the economic meaning of the dual variables for the current model, which features nodes $N1$ and $N2$, product $P1$, and a transport link between them.

### 1. Node-Product Prices ($\pi_{N,P}$)

**Intuition:**
The node-product price $\pi_{n,p}$ is the "going rate" for a specific commodity at a specific location. It represents the value to the system of having one additional unit of product $P$ available at node $N$.

**Mathematical Meaning:**
These are the dual variables associated with the node-product balance constraints (clearing conditions). For the current model:
*   $\pi_{N1,P1}$: Shadow price of $P1$ at node $N1$.
*   $\pi_{N2,P1}$: Shadow price of $P1$ at node $N2$.

From the stationarity conditions of the Lagrangian, if a transport flow $f_{N1,N2} > 0$ exists and is not at its limit, the prices are linked by:
$$
\pi_{N2,P1} - \pi_{N1,P1} = \text{Transport Cost} = 0
$$
**Economic Interpretation:**
In the Sampat framework, these are **Locational Marginal Prices (LMPs)**.
*   **Positive Prices:** Indicate the product is a "good"; the system gains surplus by having more of it.
*   **Negative Prices (Section 2.3):** If $\pi_{n,p} < 0$, the product is locally a "bad" (e.g., waste or oversupply). The system is willing to pay to have a unit removed or remediated. This occurs when local supply (bids or technology yields) exceeds local demand and outward transport capacity, forcing the system toward disposal or remediation logic.

---

### 2. Bid Rent and Scarcity Multipliers ($\mu_b, \nu_b$)

**Intuition:**
These variables represent the "missed opportunity" or "rent" associated with bid capacity. They answer the question: "How much more surplus would we generate if this participant could provide or consume one more unit?"

**Mathematical Meaning:**
These are non-negative dual variables for the upper-bound constraints on bid acceptance ($q_b \le \text{Cap}_b$).
*   $\mu_{B1}$: Scarcity rent for Supplier Bid $B1$ (Cap: 100, Price: 10).
*   $\nu_{B2}$: Scarcity rent for Consumer Bid $B2$ (Cap: 50, Price: 20).

The optimality conditions (KKT) relate these to the node prices:
*   For Supplier $B1$ at $N1$: $\pi_{N1,P1} = 10 + \mu_{B1}$ (assuming $q_{B1} > 0$).
*   For Consumer $B2$ at $N2$: $\pi_{N2,P1} = 20 - \nu_{B2}$ (assuming $q_{B2} > 0$).

**Economic Interpretation:**
*   **$\mu_{B1}$ (Producer Surplus):** The margin by which the market price at $N1$ exceeds the supplier's cost. If the bid is fully accepted ($q_{B1} = 100$), $\mu_{B1}$ is the "inframarginal rent" the supplier earns.
*   **$\nu_{B2}$ (Consumer Surplus):** The margin by which the consumer's value exceeds the market price at $N2$. If the consumer is fully served ($q_{B2} = 50$), $\nu_{B2}$ is their surplus.
*   If a bid is "marginal" (partially accepted), its corresponding multiplier is 0, and the node price exactly equals the bid price.

---

### 3. Transport Congestion Rents ($\tau_{i,j}$)

**Intuition:**
The congestion rent $\tau_{i,j}$ represents the value of expanding the "pipe" between two locations. It is the "toll" that arises when the cheapest supply cannot reach the highest-value demand due to physical constraints.

**Mathematical Meaning:**
$\tau_{N1,N2}$ is the dual variable for the transport capacity constraint ($f_{N1,N2} \le 100$). The price relationship across the link is:
$$
\pi_{N2,P1} - \pi_{N1,P1} = \text{Transport Cost} + \tau_{N1,N2}
$$
In the current model, the transport cost is $0$, so $\tau_{N1,N2} = \pi_{N2,P1} - \pi_{N1,P1}$.

**Economic Interpretation:**
In the coordinated clearing interpretation, $\tau_{N1,N2}$ captures the **locational price spread**.
*   If $\tau_{N1,N2} = 0$, the link is not congested; the prices at $N1$ and $N2$ are equal (since transport cost is 0).
*   If $\tau_{N1,N2} > 0$, the link is at its 100-unit limit. Node $N1$ (the source) likely has a lower price due to relative abundance, while node $N2$ (the sink) has a higher price due to relative scarcity. The value $\tau$ is the revenue that would be collected by the "network manager" for managing this bottleneck.

---

### Summary of Stationarity and Value Flows

The dual solution enforces a consistent value chain across the network:
1.  **Supply Side:** $\pi_{N1,P1} = \text{Supplier Cost (10)} + \text{Producer Rent } (\mu_{B1})$.
2.  **Network Side:** $\pi_{N2,P1} = \pi_{N1,P1} + \text{Congestion Rent } (\tau_{N1,N2})$.
3.  **Demand Side:** $\pi_{N2,P1} = \text{Consumer Value (20)} - \text{Consumer Rent } (\nu_{B2})$.

Under optimal clearing, these dual variables ensure that every accepted bid is profitable relative to its local price, and every flow moves product from a lower-priced node to a higher-priced node, maximizing the total coordinated surplus.

### Metadata

{
  "intent": "formal_math",
  "success": true,
  "response_metadata": {
    "response_source": "llm",
    "fallback_triggered": false,
    "raw_llm_output_present": true,
    "llm_output_length": 5138,
    "fallback_reason": null,
    "llm_exception_type": null,
    "grounding_warning_applied": false,
    "validation_warnings": [],
    "validation_fatal": [],
    "mode_used": "full",
    "grounding_mode": "paper"
  }
}
----------------------------------------------------------------------------------------------------

### Prompt
`Explain the meaning of the node-product prices \(\pi_{np}\) in the current coordinated clearing problem.`

### Response

Based on the coordinated management framework of Sampat et al. (2019), the node-product prices—denoted as $\pi_{np}$—are the foundational signals for resource allocation across the supply chain.

### 1. The Intuition: Localized Scarcity
At its simplest, $\pi_{np}$ represents the **marginal value of a product at a specific location**. If the system were suddenly gifted one additional unit of product $p$ at node $n$ (from outside the modeled bids), $\pi_{np}$ tells us exactly how much the total coordinated surplus would increase.

In this coordinated clearing context, prices are not arbitrary; they emerge from the tension between supply availability, consumer desire, and the physical constraints of transport and technology.

### 2. Mathematical Meaning: The Shadow of Balance
Mathematically, $\pi_{np}$ is the **dual variable (or shadow price)** associated with the node-product balance constraint. In your current problem state, these constraints (e.g., `balance_N1_P1` and `balance_N2_P1`) ensure that for every node $n$ and product $p$:

$$(\text{Local Supply}) + (\text{Inward Flows}) + (\text{Tech Outputs}) = (\text{Local Consumption}) + (\text{Outward Flows}) + (\text{Tech Inputs})$$

The stationarity conditions in your dual scaffold reveal how these prices must behave at optimality:
*   **For a Supplier ($B1$ at $N1$):** The condition $\mu_{B1} + \pi_{N1,P1} \geq -c_{B1}$ (where $c_{B1} = -10$) implies that if the bid is accepted ($q_{B1} > 0$), the node price $\pi_{N1,P1}$ must be at least the marginal cost of supply.
*   **For a Consumer ($B2$ at $N2$):** The condition $\nu_{B2} - \pi_{N2,P1} \geq c_{B2}$ (where $c_{B2} = 20$) implies that the node price cannot exceed the consumer's marginal utility.

### 3. Economic Interpretation: Competitive Equilibrium
Following Section 2.2 of the Sampat paper, these prices define a **competitive equilibrium**.

*   **Spatial Arbitrage:** For the transport arc between $N1$ and $N2$, the dual constraint is $\tau_{N1,N2} - \pi_{N1,P1} + \pi_{N2,P1} \geq -c_{f}$. This means the price difference between two nodes ($\pi_{N2,P1} - \pi_{N1,P1}$) is exactly equal to the transport cost plus the shadow price of the transport capacity ($\tau$). If the pipe isn't full, the price difference equals the transport cost.
*   **Technological Transformation:** If a technology $k$ were present, the prices of inputs and outputs would be linked by the yield coefficients $\gamma_{kp}$. The technology level $x_k$ only becomes positive if the value of the outputs ($\sum \gamma \pi_{out}$) exceeds the cost of inputs plus the activity cost.
*   **Negative Prices (Section 2.3):** While your current "Case A" benchmark uses positive bids, the Sampat framework explicitly allows $\pi_{np} < 0$. A negative price at a node indicates a "discommodity" (like waste), where the system is willing to pay to have a unit removed or remediated.

### 4. Application to the Current State
In the provided scaffold (Case A):
*   **Node $N1$ (Supplier):** Has a bid with a coefficient of $-10.0$. If this is the marginal supply, $\pi_{N1,P1} \approx 10$.
*   **Node $N2$ (Consumer):** Has a bid with a coefficient of $20.0$.
*   **Transport ($N1 \to N2$):** Has a cost of $0.0$ and a capacity of $100$.

Because the transport cost is zero and the capacity ($100$) exceeds the consumer's demand ($50$), the transport constraint is likely non-binding ($\tau = 0$). Economically, this forces **price equalization**: $\pi_{N1,P1} = \pi_{N2,P1} = 10$. The consumer at $N2$ enjoys a "surplus" because the local price ($10$) is lower than their maximum willingness to pay ($20$).

### Metadata

{
  "intent": "explanation",
  "success": true,
  "response_metadata": {
    "response_source": "llm",
    "fallback_triggered": false,
    "raw_llm_output_present": true,
    "llm_output_length": 3614,
    "fallback_reason": null,
    "llm_exception_type": null,
    "grounding_warning_applied": false,
    "validation_warnings": [],
    "validation_fatal": [],
    "mode_used": "full",
    "grounding_mode": "paper"
  }
}
----------------------------------------------------------------------------------------------------

### Prompt
`Verify the complementary slackness conditions for the current primal-dual pair and explain their economic interpretation.`

### Response

In the coordinated management framework of Sampat et al. (2019), complementary slackness (CS) provides the formal bridge between physical resource allocation and the economic signals (prices and rents) that sustain that allocation. For the current primal-dual pair involving bids $B_1$ and $B_2$ and transport flow $f_{N1,N2}$, the CS conditions verify that the system is in an equilibrium where no participant has an incentive to deviate.

### 1. Intuition: The "Value of the Next Unit"
Complementary slackness acts as a logical "switch." It dictates that a dual variable (a shadow price or rent) can only be non-zero if the corresponding primal constraint is "tight" (at its limit).

If there is "slack" in a capacity—for instance, if the transport line between $N_1$ and $N_2$ is not fully used—then the marginal value of additional capacity must be zero. Conversely, if a participant is willing to pay more than the current market price but is blocked by a capacity limit, that limit acquires a positive "scarcity rent."

### 2. Mathematical Meaning
The CS conditions for this system are derived from the relationship between the primal constraints and their corresponding dual multipliers ($\mu, \nu, \tau$). For the optimal solution to be valid, the product of the dual variable and the constraint slack must be zero.

**Capacity Complementary Slackness:**
$$
\begin{aligned}
\mu_{B1} \cdot (100 - q_{B1}) &= 0 \\
\nu_{B2} \cdot (50 - q_{B2}) &= 0 \\
\tau_{N1,N2} \cdot (100 - f_{N1,N2}) &= 0
\end{aligned}
$$
**Variable (Economic) Complementary Slackness:**
These relate the primal activities to their "reduced costs" (derived from the stationarity conditions in the dual summary):
$$
\begin{aligned}
q_{B1} \cdot (10 + \mu_{B1} + \pi_{N1,P1}) &= 0 \\
q_{B2} \cdot (20 - \nu_{B2} + \pi_{N2,P1}) &= 0 \\
f_{N1,N2} \cdot (0 + \tau_{N1,N2} - \pi_{N1,P1} + \pi_{N2,P1}) &= 0
\end{aligned}
$$
*Note: The stationarity conditions are adjusted here to match the standard $c^T x - \lambda^T(Ax-b)$ Lagrangian form where coefficients represent marginal surplus contribution.*

### 3. Economic Interpretation in Coordinated Clearing

In the Sampat framework, these conditions define the **Marginal Surplus Allocation**:

*   **Supplier Rent ($\mu_{B1}$):** If the supplier at $N_1$ is accepted at their full capacity ($q_{B1} = 100$), $\mu_{B1} \ge 0$. This represents the "locational profit" or scarcity rent. From the stationarity condition, $\pi_{N1,P1} = -10 - \mu_{B1}$. If the node price $\pi_{N1,P1}$ is more negative than the bid cost ($-10$), the supplier is earning a rent because the system values their disposal/supply service highly.
*   **Consumer Rent ($\nu_{B2}$):** If the consumer at $N_2$ is fully satisfied ($q_{B2} = 50$), $\nu_{B2} \ge 0$. This is the consumer surplus captured by the coordinator. The node price $\pi_{N2,P1}$ will be $\nu_{B2} - 20$.
*   **Congestion Rent ($\tau_{N1,N2}$):** If the flow $f_{N1,N2}$ reaches the 100-unit limit, $\tau_{N1,N2}$ becomes the price spread between nodes. Specifically, $\pi_{N1,P1} - \pi_{N2,P1} = \tau_{N1,N2}$. This indicates that the marginal value of the product at $N_2$ exceeds the marginal value (or cost of supply) at $N_1$ by exactly the scarcity value of the transport link.

**Interpretation of Section 2.3 (Negative Bids/Prices):**
The primal objective coefficient for $q_{B1}$ is $-10$. Consistent with Section 2.3, if this represents a supplier bid in a "coordinated management" context, a negative coefficient suggests a cost of 10 to the system. If the resulting shadow price $\pi_{N1,P1}$ is negative, it implies that the product $P_1$ at node $N_1$ is a "discommodity" (e.g., a waste product or a surplus with high storage costs). CS ensures that even with negative prices, the flow only moves from $N_1$ to $N_2$ if the "price" at $N_2$ is "higher" (less negative) than at $N_1$, accounting for the transport rent $\tau$.

**Summary of Equilibrium:**
Verification of these conditions ensures that:
1.  No flow occurs on an "unprofitable" route.
2.  No bid is accepted if its price is out-of-the-money relative to the node price $\pi$.
3.  Shadow prices only diverge between nodes when a physical constraint (like the 100-unit transport limit) is hit.

### Metadata

{
  "intent": "formal_math",
  "success": true,
  "response_metadata": {
    "response_source": "llm",
    "fallback_triggered": false,
    "raw_llm_output_present": true,
    "llm_output_length": 4236,
    "fallback_reason": null,
    "llm_exception_type": null,
    "grounding_warning_applied": false,
    "validation_warnings": [],
    "validation_fatal": [],
    "mode_used": "full",
    "grounding_mode": "solver"
  }
}
----------------------------------------------------------------------------------------------------

## Prompt Battery Pass/Fail Checklist

Each check reports whether the corresponding Case A prompt succeeded when run against `prose_state`.

In [ ]:
reasoning_regression_checks = {
    "primal_formulation_prompt_succeeded": bool(results_case_A_from_prose[0].get("success")),
    "dual_formulation_prompt_succeeded": bool(results_case_A_from_prose[1].get("success")),
    "theorem_prompt_succeeded": bool(results_case_A_from_prose[2].get("success")),
    "strong_duality_prompt_succeeded": bool(results_case_A_from_prose[3].get("success")),
    "dual_interpretation_prompt_succeeded": bool(results_case_A_from_prose[4].get("success")),
    "node_price_prompt_succeeded": bool(results_case_A_from_prose[5].get("success")),
    "complementary_slackness_prompt_succeeded": bool(results_case_A_from_prose[6].get("success")),
}

display(pd.DataFrame([
    {"check": check_name, "passed": passed}
    for check_name, passed in reasoning_regression_checks.items()
]))

## Reason / Explain From Structured Outputs

The response layer receives the interpreted state plus deterministic validation and solver outputs. The LLM is not used as the mathematical authority in this final explanation cell.

In [ ]:
response_context = {
    "type": "problem_formulation",
    "user_message": case_a_prose,
    "problem_state": prose_state,
    "market_instance": prose_market_instance,
    "semantic_plan": semantic_plan,
    "validation_result": validation_result,
    "solve_result": prose_solve_result,
    "solver_results": prose_solver_results,
    "theorem_checks": theorem_checks,
}

response_text, response_metadata = generate_response_with_metadata(
    mode="full",
    context=response_context,
    use_llm=False,
)

display(Markdown(response_text))
display(Markdown("### Response Metadata"))
print(json.dumps(response_metadata, indent=2))

## Final Regression Summary

In [ ]:
solve_objective_matches = None
if prose_solve_result["success"] and manual_solve_result["success"]:
    solve_objective_matches = abs(prose_solve_result["objective_value"] - manual_solve_result["objective_value"]) <= 1e-8

regression_summary = {
    "semantic_plan_created": isinstance(semantic_plan, dict),
    "problem_state_created": prose_state is not None,
    "matches_manual_case_a_state": not (comparison["failed_fields"] or comparison["missing_fields"] or blocking_extra_fields),
    "benign_extra_name_field_count": len(benign_extra_fields),
    "blocking_extra_field_count": len(blocking_extra_fields),
    "solver_ready": validation_result["solver_ready"],
    "case_a_compatible": validation_result["benchmark_compatibility"]["Case A"]["compatible"],
    "prose_solve_success": prose_solve_result["success"],
    "manual_solve_success": manual_solve_result["success"],
    "solve_objective_matches_when_solved": solve_objective_matches,
    "deterministic_explanation_generated": bool(response_text.strip()),
    "reasoning_prompt_battery": reasoning_regression_checks,
    "reasoning_prompt_battery_all_succeeded": all(reasoning_regression_checks.values()),
}

print(json.dumps(regression_summary, indent=2))

assert regression_summary["semantic_plan_created"]
assert regression_summary["problem_state_created"]
assert regression_summary["matches_manual_case_a_state"]
assert regression_summary["solver_ready"]
assert regression_summary["case_a_compatible"]
assert regression_summary["deterministic_explanation_generated"]
assert regression_summary["reasoning_prompt_battery_all_succeeded"]